### ISSUE TITLE
cannot unpack non-iterable numpy.float64 object

### ISSUE THREAD

**Issue by nipnipj** [ColCarroll/minimc#11]
Hello!

I got an error as decribed in the attached image.
![minimc](https://user-images.githubusercontent.com/36553373/77356327-122e0200-6d14-11ea-987a-0015563895d4.jpg)

What am I doing wrong?

Thanks & Regards

**Comment by nipnipj** [comment]
I tried editing "integrators.py". The script runs with no errors, but it is stuck at 8/2500

**Comment by ColCarroll** [comment]
Sorry, should get to this soon. Two guesses where I'll start:
1. Try putting `initial_position` into an autograd.numpy array. I seem to recall lots of stuff *only* worked with numpy objects.
2. Some of the examples no longer work, but for fun API reasons, and need to be updated. If this is copy/pasting from an example, it might need to be updated to use the new `potential` class which allows us to use different autodiff backends. Currently just theano and autograd, but I hope to add jax and tensorflow[_probability] quite soon.

**Comment by nipnipj** [comment]
I've used a fresh install of MINIMC. Then, I followes the example with:
```
import autograd
from minimc import neg_log_normal, hamiltonian_monte_carlo
samples = hamiltonian_monte_carlo(2_000, neg_log_normal(0, 0.1),
                                  initial_position=autograd.numpy.array(0))
```
Same error as in the beggining:
![bv](https://user-images.githubusercontent.com/36553373/77567367-0cabf580-6e95-11ea-8283-438b710de5e9.jpg)
